skills:
  - python
  - sql
  - machine learning
  - pandas
  - numpy
  - scikit-learn
  - tensorflow
  - pytorch
  - tableau
  - power bi
  - excel
  - statistics
  - data visualisation
  - docker
  - kubernetes
  - aws
  - azure
  - gcp
  - airflow
  - dbt
  - spark
  - communication
